### ISSUE TITLE
数据使用说明

### ISSUE THREAD

**Issue by Frankey419** [fip-lab/STANKER#1]
你好，方便给一个数据的使用说明吗？比如，post和comments是怎么关联的。还有raw_datasets文件夹下的压缩包，解压失败，不知道是不是使用方式不对

**Comment by youran521** [comment]
raw_datasets文件夹下的压缩包下载后显示文件损坏，无法使用，方便重发一下吗？另外目前给定的所有文件能完整复现吗？

**Comment by fip-lab** [comment]
> 你好，方便给一个数据的使用说明吗？比如，post和comments是怎么关联的。还有raw_datasets文件夹下的压缩包，解压失败，不知道是不是使用方式不对

感谢你的关注！现在可以通过百度网盘下载raw_datasets，链接：https://pan.baidu.com/s/1YdsECdAl0zLBkvXLD1H05w，提取码：m2c5。更多使用细节会尽快更新。

**Comment by Frankey419** [comment]
> > 你好，方便给一个数据的使用说明吗？比如，post和comments是怎么关联的。还有raw_datasets文件夹下的压缩包，解压失败，不知道是不是使用方式不对
> 
> 感谢你的关注！现在可以通过百度网盘下载raw_datasets，链接：[https://pan.baidu.com/s/1YdsECdAl0zLBkvXLD1H05w，提取码：m2c5。更多使用细节会尽快更新。](https://pan.baidu.com/s/1YdsECdAl0zLBkvXLD1H05w%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9Am2c5%E3%80%82%E6%9B%B4%E5%A4%9A%E4%BD%BF%E7%94%A8%E7%BB%86%E8%8A%82%E4%BC%9A%E5%B0%BD%E5%BF%AB%E6%9B%B4%E6%96%B0%E3%80%82)

提取码是m2c5吗，提示提取码错误哎。不知道是不是过期了，能否再分享一下吗？
